package hashTable;

import java.util.HashMap;
import java.util.Map;

/**
 * author： 张亚飞
 * time：2016/9/7  11:10
 */
//Given two strings s and t which consist of only lowercase letters.
//
//        String t is generated by random shuffling string s and then add one more letter at a random position.
//
//        Find the letter that was added in t.
//
//        Example:
//
//        Input:
//        s = "abcd"
//        t = "abcde"
//
//        Output:
//        e
//
//        Explanation:
//        'e' is the letter that was added.
    //字符串t是由字符串s，随机打乱之后，然后添加一张而成
    //找出随意添加的那一张
public class FindtheDifference_389 {
    public static char findTheDifference(String s, String t) {
        Map<Character,Integer> map = new HashMap<>();
        for (int i = 0; i <s.length() ; i++) {
            if (map.containsKey(s.charAt(i))){
                map.replace(s.charAt(i),map.get(s.charAt(i))+1);
            }else {
                map.put(s.charAt(i),1);
            }
        }


        for (int i = 0; i <t.length() ; i++) {
            if (map.containsKey(t.charAt(i))){
                if (map.get(t.charAt(i))>1){
                    map.replace(t.charAt(i),map.get(t.charAt(i))-1);
                }else {
                    map.remove(t.charAt(i));
                }
            }else {
                return t.charAt(i);
            }
        }
        return s.charAt(0);
    }


    public static void main(String[] args) {

    }
}
